import {
  SiFacebook,
  SiGithub,
  SiGithubpages,
  SiGitlab,
  SiDevdotto,
  SiWakatime,
  SiFreecodecamp,
  SiInstagram,
  SiTiktok,
  SiPinterest,
  SiTwitch,
  SiX,
  SiYoutube,
  SiSpotify,
  SiLeetcode,
  SiCodechef,
  SiGeeksforgeeks,
  SiHackerrank,
  SiHackerearth,
  SiCodewars,
  SiHackthebox,
  SiTryhackme,
  SiHashnode,
  SiMedium,
  SiSubstack,
  SiCodepen,
  SiCodesandbox,
  SiStackblitz,
  SiStackoverflow,
  SiDribbble,
  SiBehance,
  SiBitbucket,
  SiCodeberg,
  SiDiscord,
  SiBluesky,
  SiMastodon,
  SiReddit,
  SiQuora,
  SiBuymeacoffee,
  SiPatreon,
  SiKofi,
  SiCodeforces,
  SiKaggle,
  SiHuggingface,
  SiProducthunt,
  SiDocker,
  SiNpm,
  SiPypi,
  SiVercel,
  SiNetlify,
  SiRender,
  SiRailway,
  SiCloudflare,
  SiNotion,
  SiFigma,
  SiTelegram,
  SiSlack,
  SiGooglescholar,
  SiOrcid,
  SiItchdotio,
  SiSteam,
  SiOpencollective,
  SiDailydotdev,
  SiGmail,
} from "react-icons/si";
import { BsLinkedin } from "react-icons/bs";
import type { SocialIdentity } from "./socialProvider";

export const PROVIDER_REGISTRY: Record<string, Omit<SocialIdentity, 'handle' | 'url'>> = {
  "github.com": { provider: "GitHub", Icon: SiGithub, color: "#181717" },
  "github.io": { provider: "GitHub Pages", Icon: SiGithubpages, color: "#222222" },
  "gitlab.com": { provider: "GitLab", Icon: SiGitlab, color: "#FC6D26" },
  "bitbucket.org": { provider: "Bitbucket", Icon: SiBitbucket, color: "#0052CC" },
  "codeberg.org": { provider: "Codeberg", Icon: SiCodeberg, color: "#2185D0" },
  "wakatime.com": { provider: "WakaTime", Icon: SiWakatime, color: "#38A4FF" },

  "dev.to": { provider: "DEV", Icon: SiDevdotto, color: "#0A0A0A" },
  "hashnode.dev": { provider: "Hashnode", Icon: SiHashnode, color: "#2962FF" },
  "hashnode.com": { provider: "Hashnode", Icon: SiHashnode, color: "#2962FF" },
  "medium.com": { provider: "Medium", Icon: SiMedium, color: "#000000" },
  "substack.com": { provider: "Substack", Icon: SiSubstack, color: "#FF6719" },
  "daily.dev": { provider: "daily.dev", Icon: SiDailydotdev, color: "#FFFFFF" },

  "twitter.com": { provider: "X", Icon: SiX, color: "#000000" },
  "x.com": { provider: "X", Icon: SiX, color: "#000000" },
  "linkedin.com": { provider: "LinkedIn", Icon: BsLinkedin, color: "#0A66C2" },
  "bsky.app": { provider: "Bluesky", Icon: SiBluesky, color: "#0285FF" },
  "mastodon.social": { provider: "Mastodon", Icon: SiMastodon, color: "#6364FF" },
  "discord.gg": { provider: "Discord", Icon: SiDiscord, color: "#5865F2" },
  "discord.com": { provider: "Discord", Icon: SiDiscord, color: "#5865F2" },
  "reddit.com": { provider: "Reddit", Icon: SiReddit, color: "#FF4500" },
  "quora.com": { provider: "Quora", Icon: SiQuora, color: "#B92B27" },
  "t.me": { provider: "Telegram", Icon: SiTelegram, color: "#26A5E4" },
  "telegram.me": { provider: "Telegram", Icon: SiTelegram, color: "#26A5E4" },
  "slack.com": { provider: "Slack", Icon: SiSlack, color: "#4A154B" },
  "gmail.com": { provider: "Gmail", Icon: SiGmail, color: "#D14836" },

  "codepen.io": { provider: "CodePen", Icon: SiCodepen, color: "#000000" },
  "codesandbox.io": { provider: "CodeSandbox", Icon: SiCodesandbox, color: "#151515" },
  "stackblitz.com": { provider: "StackBlitz", Icon: SiStackblitz, color: "#1374EF" },
  "stackoverflow.com": { provider: "Stack Overflow", Icon: SiStackoverflow, color: "#F58025" },

  "leetcode.com": { provider: "LeetCode", Icon: SiLeetcode, color: "#FFA116" },
  "codechef.com": { provider: "CodeChef", Icon: SiCodechef, color: "#5B4638" },
  "geeksforgeeks.org": { provider: "GeeksforGeeks", Icon: SiGeeksforgeeks, color: "#2F8D46" },
  "hackerrank.com": { provider: "HackerRank", Icon: SiHackerrank, color: "#2EC866" },
  "codeforces.com": { provider: "Codeforces", Icon: SiCodeforces, color: "#B13434" },
  "kaggle.com": { provider: "Kaggle", Icon: SiKaggle, color: "#20BEFF" },
  "huggingface.co": { provider: "Hugging Face", Icon: SiHuggingface, color: "#FFD21E" },
  "hackerearth.com": { provider: "HackerEarth", Icon: SiHackerearth, color: "#2C3454" },
  "codewars.com": { provider: "Codewars", Icon: SiCodewars, color: "#B1361E" },
  "hackthebox.eu": { provider: "Hack The Box", Icon: SiHackthebox, color: "#9FEF00" },
  "tryhackme.com": { provider: "TryHackMe", Icon: SiTryhackme, color: "#212C42" },

  "hub.docker.com": { provider: "Docker Hub", Icon: SiDocker, color: "#2496ED" },
  "docker.com": { provider: "Docker Hub", Icon: SiDocker, color: "#2496ED" },
  "npmjs.com": { provider: "NPM", Icon: SiNpm, color: "#CB3837" },
  "npmjs.org": { provider: "NPM", Icon: SiNpm, color: "#CB3837" },
  "pypi.org": { provider: "PyPI", Icon: SiPypi, color: "#3775A9" },
  "vercel.com": { provider: "Vercel", Icon: SiVercel, color: "#000000" },
  "vercel.app": { provider: "Vercel", Icon: SiVercel, color: "#000000" },
  "netlify.com": { provider: "Netlify", Icon: SiNetlify, color: "#00C7B7" },
  "netlify.app": { provider: "Netlify", Icon: SiNetlify, color: "#00C7B7" },
  "cloudflare.com": { provider: "Cloudflare", Icon: SiCloudflare, color: "#F38020" },
  "onrender.com": { provider: "Render", Icon: SiRender, color: "#000000" },
  "railway.app": { provider: "Railway", Icon: SiRailway, color: "#000000" },

  "producthunt.com": { provider: "Product Hunt", Icon: SiProducthunt, color: "#DA552F" },
  "buymeacoffee.com": { provider: "Buy Me a Coffee", Icon: SiBuymeacoffee, color: "#FFDD00" },
  "patreon.com": { provider: "Patreon", Icon: SiPatreon, color: "#FF424D" },
  "ko-fi.com": { provider: "Ko-fi", Icon: SiKofi, color: "#FF5E5B" },
  "opencollective.com": { provider: "Open Collective", Icon: SiOpencollective, color: "#7FADF2" },

  "instagram.com": { provider: "Instagram", Icon: SiInstagram, color: "#E4405F" },
  "youtube.com": { provider: "YouTube", Icon: SiYoutube, color: "#FF0000" },
  "youtu.be": { provider: "YouTube", Icon: SiYoutube, color: "#FF0000" },
  "twitch.tv": { provider: "Twitch", Icon: SiTwitch, color: "#9146FF" },
  "facebook.com": { provider: "Facebook", Icon: SiFacebook, color: "#1877F2" },
  "fb.com": { provider: "Facebook", Icon: SiFacebook, color: "#1877F2" },
  "tiktok.com": { provider: "TikTok", Icon: SiTiktok, color: "#000000" },
  "pinterest.com": { provider: "Pinterest", Icon: SiPinterest, color: "#BD081C" },
  "pinterest.co.uk": { provider: "Pinterest", Icon: SiPinterest, color: "#BD081C" },
  "open.spotify.com": { provider: "Spotify", Icon: SiSpotify, color: "#1ED760" },

  "freecodecamp.org": { provider: "freeCodeCamp", Icon: SiFreecodecamp, color: "#0A0A23" },
  "scholar.google.com": { provider: "Google Scholar", Icon: SiGooglescholar, color: "#4285F4" },
  "orcid.org": { provider: "ORCID", Icon: SiOrcid, color: "#A6CE39" },

  "notion.so": { provider: "Notion", Icon: SiNotion, color: "#000000" },
  "notion.site": { provider: "Notion", Icon: SiNotion, color: "#000000" },
  "dribbble.com": { provider: "Dribbble", Icon: SiDribbble, color: "#EA4C89" },
  "behance.net": { provider: "Behance", Icon: SiBehance, color: "#1769FF" },
  "figma.com": { provider: "Figma", Icon: SiFigma, color: "#F24E1E" },

  "steamcommunity.com": { provider: "Steam", Icon: SiSteam, color: "#000000" },
  "store.steampowered.com": { provider: "Steam", Icon: SiSteam, color: "#000000" },
  "itch.io": { provider: "Itch.io", Icon: SiItchdotio, color: "#FA5C5C" },
};