# action.yml
name: 'icommit'
description: 'A native GitHub Action that synthesizes your raw Git activity into verified artifacts.'
author: 'riteshraj'

branding:
  icon: 'terminal' 
  color: 'green'  

runs:
  using: 'docker'
  image: 'Dockerfile' 