# action.yml
name: 'icommit-io'
description: 'A native GitHub Action that synthesizes your raw Git activity into verified artifacts.'
author: '@riteshraj-shetage'

branding:
  icon: 'terminal' 
  color: 'green'  

runs:
  using: 'docker'
  image: 'Dockerfile' 