name: Pipeline Integration Test

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-engine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute containerized test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify data
        run: cat frontend/public/gh-data.json